name: Slack Alert Practice

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  healthcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Release API Health Check
        uses: jtal/url-health-check-action@v3
        with: 
          url: ${{secrets.RELEASE_URI}}
          max-attempts: 3
          retry-delay: 1s

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Health-Check
          fields: repo,message,commit,action,eventName,ref,workflow,job,took
          github_token: ${{ secrets.ACCESS_TOKEN_GIT }}

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }} # required
        if: always() # 스크립트 성공/실패 여부에 상관없이 항상 수행되도록 설정
